In [4]:
# 1. Creating Matrices

# Name: Kayla Bansian Genovea
Matrix_1 = [
    [11, 2, 7],  # KBG
    [1, 1, 5]     # aae
]

# Student Number: 2023-4-0429
Matrix_2 = [
    [2, 0, 2],     # first 3 digits
    [4, 2, 9]      # last 3 digits
]

print("1st Matrix:")
print(Matrix_1)
print("\n2nd Matrix:")
print(Matrix_2)

1st Matrix:
[[11, 2, 7], [1, 1, 5]]

2nd Matrix:
[[2, 0, 2], [4, 2, 9]]


In [5]:
# 2. Matrix Addition
import numpy as np

A = np.array(Matrix_1)
B = np.array(Matrix_2)
C = A + B 

print("\n3rd Matrix:")
print(C)


3rd Matrix:
[[13  2  9]
 [ 5  3 14]]


In [6]:
# 3. Scalar Multiplication

D = 2 * A

print("\n4th Matrix:")
print(D)


4th Matrix:
[[22  4 14]
 [ 2  2 10]]


In [9]:
# 4. Matrix Transpose

E = B.T

print("\n5th Matrix:")
print(E)


5th Matrix:
[[2 4]
 [0 2]
 [2 9]]


In [10]:
# 5. Matrix Multiplication

F = C @ E

print("\n6th Matrix:")
print(F)


6th Matrix:
[[ 44 137]
 [ 38 152]]


In [11]:
# 6. Sum of All Elements

sum_Matrix_3 = np.sum(C)

print("\nSum:")
print(sum_Matrix_3)


Sum:
46


In [13]:
# 7. Zero Matrix

G = np.zeros((2, 3), dtype = int)

print("\n7th Matrix:")
print(G)


7th Matrix:
[[0 0 0]
 [0 0 0]]
